config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]

  devise_scope :user do
    resources :users, controller: :users
  end

  resources :products
  resources :customers
  resources :orders do
  resources :order_items, except: [:index, :show], controller: 'orders/order_items'
  end
  get 'orders/order_items/unit_price/:id' => 'orders/order_items#unit_price', as: :unit_price

    root to:'static_pages#home'

  get :send_order_mail, to: 'orders#send_order_mail', as: :send_order_mail
  
  

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items, dependent: :destroy

  validates_presence_of :user


  paginates_per 25

  #Scopes search
  scope :search, -> (query) { joins(:user).where("lower(users.name) LIKE ?", "%#{query.downcase}%")}

  end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true 

  def valor_total
  	quantity.to_i * unit_price
  end
end

app/controllers/orders/order_items_controller.rb
class Orders::OrderItemsController < ApplicationController
  before_action :set_order, except: [:unit_price, :total_price]
  before_action :set_order_item, except: [:new, :create, :unit_price, :total_price]
  
  def unit_price
   #binding.pry
    @unit_price = Product.find(params[:id]).get_price(current_user.costumer_type)
  end

  # GET /order_items
  # GET /order_items.json
  def index
    @order_items = OrderItem.all
  end

  # GET /order_items/1
  # GET /order_items/1.json
  def show
  end

  # GET /order_items/new
  def new
    @order = Order.find(params[:order_id])
    @order_item = OrderItem.new
  end

  # GET /order_items/1/edit
  def edit
    
  end

  # POST /order_items
  # POST /order_items.json
  def create
    @order = Order.find(params[:order_id])
    @order_item = OrderItem.new(order_item_params)
    @order_item.order = @order
    @order_item.total_price =  @order_item.valor_total
    
    
    respond_to do |format|
      if @order_item.save
        format.html { redirect_to @order, notice: 'Item incluido com sucesso.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    respond_to do |format|
      if @order_item.update(order_item_params)
        format.html { redirect_to @order, notice: 'Order item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_item }
      else
        format.html { render :edit }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    title = @order_item.product.name

    if @order_item.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @order
    else
      flash[:error] = "There was an error deleting the item."
      render :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    def set_order
      @order = Order.find(params[:order_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params[:order_item][:unit_price].gsub!(/[R$.\s]/, '').gsub!(',', '.') if params[:order_item][:unit_price].present?
      params[:order_item][:total_price].gsub!(/[R$.\s]/, '').gsub!(',', '.') if params[:order_item][:total_price].present?
      params.require(:order_item).permit(:product_id, :quantity, :unit_price, :total_price)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json

  def send_order_mail
    @order = Order.find(params[:id])
    User.where(admin: true).each do |admin|
      AdminMailer.welcome_email(current_user, @order, admin).deliver_now
    end
    flash[:notice] = "O Pedido de N° \"#{@order.id}\" foi enviado com sucesso!"      
    redirect_to orders_path
  end

  def index
    @order = if params[:search]
        #AQUI VOC~E POE A PESQUISA
        if current_user.admin? 
          @orders = Order.all.search(params[:search]).order(id: :desc).page(params[:page])
        else
          @orders = Order.search(params[:search]).where(user: current_user).order(id: :desc).page(params[:page])
        end
    else # DAqui para baixo não tem pesquisa
      if current_user.admin? 
        @orders = Order.all.order(id: :desc).page(params[:page])
      else
        @orders = Order.where(user: current_user).order(id: :desc).page(params[:page])
      end
    end

  end
  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

  end

  # GET /orders/new
  def new
    @order = Order.create(user: current_user)

    redirect_to @order
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Pedido criado com sucesso.' }
        # AdminMailer.welcome_email(current_user, @order).deliver_later
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Pedido atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Pedido excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
     params.require(:order).permit(:user_id, order_items_attributes: [:product_id, :quantity, :unit_price, :total_price])
   end

 end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/order_items/_form.html.erb
    <%= form_for [@order, @order_item], :html => { :class => "form-horizontal order_item" } do |f| %>
  <div class="form-group">
    <%= f.label :product_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">   
      <%= select("order_item", "product_id", Product.where(inactive: false).collect {|p| [p.name, p.id]}, {include_blank: 'Selecione o Produto'}, {:class => 'form-control'})%>
    </div>
    <%=f.error_span(:product_id) %>
  </div>
  
  <div class="form-group">
    <%= f.label :quantity, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :quantity, :class => 'form-control' %>
    </div>
    <%=f.error_span(:quantity) %>
  </div>
  
  <div class="form-group">
    <%= f.label :unit_price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :unit_price, :class => 'form-control money', readonly: true %>
    </div>
    <%=f.error_span(:unit_price) %>
  </div>
 
  <div class="form-group">
    <%= f.label :total_price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :total_price, :class => 'form-control money', readonly: true  %>
    </div>
    <%=f.error_span(:total_price) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
     
      <%= link_to t('.back', :default => t("helpers.links.back")),
              order_path(@order) , :class => 'btn btn-default' %>
    </div>
<% end %>

app/views/orders/order_items/edit.html.erb
<%- model_class = OrderItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/order_items/index.html.erb
<%- model_class = OrderItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_order_item_path,
            :class => 'btn btn-primary' %>
            </br></br>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:unit_price) %></th>
      <th><%= model_class.human_attribute_name(:total_price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <!--<th><%=t '.actions', :default => t("helpers.actions") %></th>-->
    </tr>
  </thead>
  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= link_to order_item.id, order_item_path(order_item) %></td>
        <td><%= order_item.product.name %></td>
        <td><%= order_item.quantity %></td>
        <td><%= order_item.unit_price %></td>
        <td><%= order_item.total_price %></td>
        <td><%=l order_item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_order_item_path(order_item), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      order_item_path(order_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/order_items/new.html.erb
<%- model_class = OrderItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/order_items/show.html.erb
<%- model_class = OrderItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @order_item.product.name unless order_item.product.blank? %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @order_item.quantity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unit_price) %>:</strong></dt>
  <dd><%= @order_item.unit_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_price) %>:</strong></dt>
  <dd><%= @order_item.total_price %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              order_items_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_order_item_path(@order_item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              order_item_path(@order_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/orders/order_items/unit_price.js.erb
$('#order_item_unit_price').val('<%= @unit_price %>');

    $('.money').priceFormat({
      prefix: 'R$ ',
      centsSeparator: ',',
      thousandsSeparator: '.'
    });