config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]

  devise_scope :user do
    resources :users, controller: :users
  end

  resources :products
  resources :customers
  resources :orders do
  resources :order_items, except: [:index, :show], controller: 'orders/order_items'
  end
  get 'orders/order_items/unit_price/:id' => 'orders/order_items#unit_price', as: :unit_price

    root to:'static_pages#home'

  get :send_order_mail, to: 'orders#send_order_mail', as: :send_order_mail
  
  

  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	# #belongs_to :user
	# #has_many :order

	# validates_presence_of :name
	# validates :cnpj_cpf, numericality: true


	# def name
 #     read_attribute(:name).try(:titleize)
 #  	end

 #  	def company_name
 #     read_attribute(:company_name).try(:titleize)
 #  	end
	
	# def customer_type_to_s
	# 	# ["Preço Loja", "0"], ["Tabela 1", "1"], ["Tabela 2", "2"]
	# 	case costumer_type
	# 	when 0
	# 		"Preço Loja"
	# 	when 1
	# 		"Tabela 1"
	# 	when 2
	# 		"Tabela 2"
	#     end
	# end
		
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Cliente criado com sucesso.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Cliente atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Cliente excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :company_name, :cnpj_cpf, :ie_rg, :phone, :cell_phone, :email, :address, :number, :neighborhood, :city, :postal_code, :state, :costumer_type)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
  <%= form_for @customer, :html => { :class => "form-horizontal customer" } do |f| %>
  <h5>*Insira seus dados para dar continuidade ao uso do sistema</h5>
  <% if @customer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :company_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :company_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:company_name) %>
  </div>
  <div class="form-group">
    <%= f.label :cnpj_cpf, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cnpj_cpf, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cnpj_cpf) %>
  </div>
  <div class="form-group">
    <%= f.label :ie_rg, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ie_rg, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ie_rg) %>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
  </div>
    <div class="form-group">
    <%= f.label :cell_phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cell_phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cell_phone) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:number) %>
  </div>
  <div class="form-group">
    <%= f.label :neighborhood, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :neighborhood, :class => 'form-control' %>
    </div>
    <%=f.error_span(:neighborhood) %>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%=f.error_span(:city) %>
  </div>
  <div class="form-group">
    <%= f.label :postal_code, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :postal_code, :class => 'form-control' %>
    </div>
    <%=f.error_span(:postal_code) %>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
    <%=f.error_span(:state) %>
  </div>
  <div class="form-group">
    <%= f.label :costumer_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select(:costumer_type, [["Preço Loja", "0"], ["Tabela 1", "1"], ["Tabela 2", "2"]]) %>
    </div>
    <%=f.error_span(:costumer_type) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn btn-warning' %>
    </div>
  </div>

<% end %>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>
            </br></br>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:company_name) %></th>
      <th><%= model_class.human_attribute_name(:cnpj_cpf) %></th>
      <th><%= model_class.human_attribute_name(:ie_rg) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:cell_phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <!--<th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:neighborhood) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:postal_code) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>-->
      <th><%= model_class.human_attribute_name(:costumer_type) %></th>
      <!--<th><%= model_class.human_attribute_name(:created_at) %></th>-->
      <!--<th><%=t '.actions', :default => t("helpers.actions") %></th>-->
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to customer.name, customer_path(customer) %></td>
        <td><%= customer.company_name %></td>
        <td><%= customer.cnpj_cpf %></td>
        <td><%= customer.ie_rg %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.cell_phone %></td>
        <td><%= customer.email %></td>
        <!--<td><%= customer.address %></td>
        <td><%= customer.number %></td>
        <td><%= customer.neighborhood %></td>
        <td><%= customer.city %></td>
        <td><%= customer.postal_code %></td>
        <td><%= customer.state %></td>-->
        <td><%= customer.customer_type_to_s %></td>
        <!--<td><%=l customer.created_at %></td>-->
        <td>
        <%= link_to t('.show', :default => t("helpers.links.show")),
                      customer_path(customer), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-warning btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
 <%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @customer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:company_name) %>:</strong></dt>
  <dd><%= @customer.company_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cnpj_cpf) %>:</strong></dt>
  <dd><%= @customer.cnpj_cpf %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ie_rg) %>:</strong></dt>
  <dd><%= @customer.ie_rg %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @customer.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cell_phone) %>:</strong></dt>
  <dd><%= @customer.cell_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @customer.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @customer.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @customer.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neighborhood) %>:</strong></dt>
  <dd><%= @customer.neighborhood %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @customer.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:postal_code) %>:</strong></dt>
  <dd><%= @customer.postal_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @customer.state %></dd>
  <!--Veja Model Customer-->
  <dt><strong><%= model_class.human_attribute_name(:costumer_type) %>:</strong></dt>
  <dd><%= @customer.customer_type_to_s %></dd>
</dl>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn btn-warning' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>